spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thiscode_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: cire
    password: 1234
  data:
    mongodb:
      uri: mongodb+srv://cire:QrW97rORugCJ6snc@cluster0.b2k8fhk.mongodb.net/chat?retryWrites=true&w=majority

  security:
    login-page-uri: http://localhost:80/login
    oauth2:
      redirect-uri: http://localhost:80/api/login/oauth2/code/{registrationId}
      client:
        registration:
          google:
            client-id: 833958086342-8qnk6sqc3vqhkbmnsnjpv67qslcnv7a9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:80/api/login/oauth2/code/{registrationId}
            scope: profile,email
            #                        scope: openid,profile,emailJwtTokenProvider
  jwt:
    secret-key: secretdasdasdasdasdaKeysecretdasdasdasdasdaKeysecretdasdasdasdasdaKeysecretdasdasdasdasdaKeysecretdasdasdasdasdaKeysecretdasdasdasdasdaKey

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dltpwns0@gmail.com
    password: wkpu qcrq mopn ijjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
#      springframework:
#        security: trace
    security: trace
    root: info
